### ISSUE TITLE
Unable to update gist HttpError: Not Found

### ISSUE THREAD

**Issue by Suvink** [matchai/bird-box#11]
This throws out when I try to run this!

**Comment by matchai** [comment]
Can you share an example repo where this issue is being encountered?
Please ensure that your `GIST_ID` is being correctly set.

**Comment by Suvink** [comment]
The problem was I hardcoded `gistID` and `personalAccessToken` so when I moved them into separate `.env` file, it worked. Now the problem is I repurposed `Bird-box` into something else and the Github Action throws out another error. 

`internal/modules/cjs/loader.js:985
  throw err;
  ^
Error: Cannot find module 'request-promise'
`
But this works fine in my local computer.

You can see my repo here.
https://github.com/Suvink/corona-stats-gist

**Comment by matchai** [comment]
It looks like you're no longer running into those issues on the latest action runs, so I'll go ahead and close this issue. 😊
