### ISSUE TITLE
Where are the repo secrets ?

### ISSUE THREAD

**Issue by kissu** [matchai/bird-box#7]
Hi, a pretty noob-ish question.
I'm stuck at the `Go to the repo Settings > Secrets` part.
But as far as I understood, we need to somehow pass ENV variables to a repo ? I clearly don't know where those are and didn't find anything related on Google. :sweat_smile:

**Comment by matchai** [comment]
You should be able to access it via https://github.com/kissu/bird-box/settings/secrets.

Keep in mind that bird-box is dependant on [GitHub Actions](https://github.com/features/actions), which has not yet been made available to everyone yet, as it is still in closed beta. If you do not see the "Secrets" page, it's possible that you don't have access to the feature yet. 🙂
